add-error-boundary
SpaceyaTech/SYT-Web-Redesign pull request #118
Opened 2024-01-25 08:19 UTC by Ase020

Add Error Boundary to the app and display Error500 page.

2024-01-26 07:19 UTC, sonylomo requested changes

2024-01-26 07:19 UTC, sonylomo commented on src/APP/pages/aboutUs/sections/PartnerCTA.jsx
> +              download="SpaceYaTech_Internship_Program_2023.pdf"
I removed this on purpose. it's preventing the file from opening on a new tab first. Lawrence and Weshy complained about this behavior this week.
```suggestion

```

2024-01-26 07:19 UTC, sonylomo commented on src/APP/pages/errorPages/Error500.jsx
I suggest you use the `a` tag for hyperlinks/external links.

2024-01-30 18:58 UTC, sonylomo approved these changes

2024-01-30 19:00 UTC, collinskasyoki approved these changes

2024-01-30 19:05 UTC, merged