Refetch-blog
SpaceyaTech/SYT-Web-Redesign pull request #119
Opened 2024-01-25 08:46 UTC by Ase020

Refetch blog on title_slug change. Fix the failure to load the clicked blog on the related articles sections.

Set `p` tags font size to 15px for uniform font sizes on the blog pages.

2024-01-26 07:24 UTC, sonylomo requested changes

2024-01-26 07:24 UTC, sonylomo commented on src/APP/pages/aboutUs/sections/PartnerCTA.jsx
> +              download="SpaceYaTech_Internship_Program_2023.pdf"
This `download` attribute was intentionally removed.
```suggestion

```

2024-01-26 07:24 UTC, sonylomo approved these changes

2024-01-27 08:03 UTC, collinskasyoki approved these changes

2024-01-27 08:03 UTC, merged