add colabs cover
SpaceyaTech/SYT-Web-Redesign pull request #124
Opened 2024-01-30 06:27 UTC by Ase020

Added the CoLabs cover
![Screenshot 2024-01-30 092705](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/68052150/12d028ce-af62-4239-a4d5-e6e19076e3a7)

2024-01-30 19:03 UTC, sonylomo requested changes
Mobile view is broken:

<img width="437" alt="Screenshot 2024-01-30 at 10 02 12 PM" src="https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/49971500/541b3454-922b-4c33-80f0-a4e296c2825c">

2024-01-30 19:26 UTC, Ase020 commented
> Mobile view is broken:
> 
> <img alt="Screenshot 2024-01-30 at 10 02 12 PM" width="437" src="https://private-user-images.githubusercontent.com/49971500/300931054-541b3454-922b-4c33-80f0-a4e296c2825c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDI5NzUsIm5iZiI6MTcwNjY0MjY3NSwicGF0aCI6Ii80OTk3MTUwMC8zMDA5MzEwNTQtNTQxYjM0NTQtOTIyYi00YzMzLTgwZjAtYTRlMjk2YzI4MjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE5MjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZmI2Y2E1MDA0MGY5ZDJhZDhiMjNjNjc5MGUxYjIyNjRmOTRiOWU3ZTE1NTE4ZGY0M2M0N2VmYzI4Y2M1ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OmG0UWLwvy9LBFqfMzKXg5cnoJ9W6p8a7qwgzrikLLA">

@sonylomo which screen size is this? I don't see it on my end.

2024-01-30 19:29 UTC, sonylomo commented
I've just reloaded it and it's gone...my bad. 😁

2024-01-30 19:29 UTC, sonylomo approved these changes

2024-01-31 00:43 UTC, JimmyTron approved these changes

2024-01-31 00:43 UTC, merged