Blog styles
SpaceyaTech/SYT-Web-Redesign pull request #209
Opened 2024-06-28 11:22 UTC by Joe-Mwangi

[Have you read the contributing guidelines ?](https://github.com/SpaceyaTech/SYT-Web-Redesign/blob/Dev/docs/CONTRIBUTING.md)

# What is the purpose of your *pull request*?

- To fix some  styles not applying on html tags. eg. headings  and also Fix Duplicate Blog Content Issue i encountered.
- Fixes #195
 - [x] Bug fix
 - [ ] New feature

# Proposed changes
- Replaced predefined CSS classes for blog content styling with Tailwind CSS Typography classes.
- This change ensures consistent and responsive typography styling across the blog content.
- I also updated the useEffect hook in the BlogBody component to set the innerHTML of the blog content container directly instead of appending to it, which prevents duplicate content from being rendered when the blogBody prop changes.
# Warning

# Please read these points carefully and answer honestly with an `X`
into all the boxes. Example : [X] 

Before submitting a *pull request* make sure you have:

 - [x] Read the guidelines for contributing.
 - [ ] Wrote some tests.
 - [x] Respected the linting guidelines.

2024-07-09 08:56 UTC, sonylomo requested changes

2024-07-09 08:56 UTC, sonylomo commented on src/pages/blog2/sections/BlogBody.jsx
> +          />
The text styles are inconsistent with the [original Figma Designs](https://www.figma.com/design/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?node-id=6943-12373&m=dev) i.e it's too small for a blog post and the color is too light.

2024-07-09 08:56 UTC, sonylomo commented on src/pages/blog2/sections/BlogBody.jsx
> +          />
Thanks for adding the typography, that was a good call.

2024-07-21 22:46 UTC, JimmyTron commented
there's a merge conflict in the offing here.

2024-08-08 11:34 UTC, sonylomo commented
Hey @Joe-Mwangi 👋🏾 

Are you still working on this?

2024-08-17 06:44 UTC, Joe-Mwangi commented
> Hey @Joe-Mwangi 👋🏾
> 
> Are you still working on this?

Yes am working on it. Thanks for the reminder

2024-09-09 14:46 UTC, JimmyTron approved these changes
LGTM 👌

2024-09-10 08:48 UTC, Ase020 approved these changes

2024-09-17 16:49 UTC, sonylomo approved these changes

2024-09-17 16:50 UTC, merged