Feat/auth integration
SpaceyaTech/SYT-Web-Redesign pull request #66
Opened 2023-10-02 13:43 UTC by sonylomo

# Description
This PR implements Login functionality using `axios`. I've created a custom `AuthProvider` to handle global auth requirements.

2023-10-05 14:03 UTC, JimmyTron requested changes
LG and also tried it and it works
 but still there are some security recommendations we could take into consideration.

2023-10-19 18:53 UTC, JimmyTron approved these changes
LGTM

2023-10-24 18:14 UTC, McbullIan commented
Hey @sonylomo @JimmyTron Was this already merged? I can't seem to find the branch.

2023-10-30 09:35 UTC, Ase020 approved these changes

2023-10-30 09:35 UTC, merged