Code refactoring
SpaceyaTech/SYT-Web-Redesign pull request #85
Opened 2023-11-27 09:20 UTC by Ase020

2023-11-28 18:40 UTC, McbullIan commented
@JimmyTron is this the PR you need he;p reviewing?

2023-11-29 06:16 UTC, Ase020 commented
@sonylomo these are the changes that I made on the PR:

- Resized the podcastCards on the landing page
![Screenshot 2023-11-29 090420](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/68052150/d47d3b24-45f6-499d-accf-41a9b86ab731)

- Removed the Creative Team section on the About Us page
- Set the object-fit from cover to contain on the Event cards on the community page
- Deleted redundant files such as Headers and Footers

2023-11-29 17:52 UTC, McbullIan commented
Hey @Ase020 . I've started reviewing your code and should be done by tomorrow. And could you please include a description in all your PRs moving forward?  It helps when it comes to reviewing your code and knowing exactly where I need to start.

2023-12-02 18:28 UTC, JimmyTron approved these changes

2023-12-15 06:50 UTC, collinskasyoki commented on src/APP/pages/aboutUs/sections/PartnerCTA.jsx
I am not sure if the commented parts will be implemented in the future or not. If not, they should be removed.

2023-12-15 06:51 UTC, collinskasyoki approved these changes

2023-12-15 13:46 UTC, JimmyTron reviewed
Lets remove anything that is commented out to keep the codebase clean

2023-12-23 10:04 UTC, JimmyTron requested changes
Resolve the conflicts then ill be able to merge

2023-12-24 17:48 UTC, JimmyTron approved these changes

2023-12-24 17:49 UTC, JimmyTron approved these changes

2024-01-02 09:45 UTC, closed without merging